baseURL = 'https://gautam6599123-collab.github.io/'
languageCode = 'en-us'
title = 'Gautam Singh'
theme = 'mono'

[markup]
  [markup.highlight]
    noClasses = false
    style = "bw" 
  
  [markup.goldmark.renderer]
    unsafe = true
  
  [markup.goldmark.extensions]
    [markup.goldmark.extensions.passthrough]
      enable = true
      [markup.goldmark.extensions.passthrough.delimiters]
        block = [['\[', '\]'], ['$$', '$$']]
        inline = [['\(', '\)'], ['$', '$']]

[menus]
  [[menus.main]]
  name = 'Home'
  pageRef = '/'
  weight = 10

  [[menus.main]]
  name = 'Posts'
  pageRef = '/posts'
  weight = 20

  [[menus.main]]
  name = 'Tags'
  pageRef = '/tags'
  weight = 30

  [[menus.main]]
  name = 'Projects'
  pageRef = '/projects'
  weight = 40

